### ISSUE TITLE
ExecStart=-

### ISSUE THREAD

**Issue by martinbreu** [samply/open-telekom-cloud#12]
Active: failed (Result: exit-code) since Thu 2019-09-26 13:19:54 UTC; 22h ago
  Process: 911 ExecStart=/usr/bin/docker network create gba (code=exited, status=1/FAILURE)
 Main PID: 911 (code=exited, status=1/FAILURE)

Sep 26 13:19:54 server.openstacklocal systemd[1]: Starting Creates docker network...
Sep 26 13:19:54 server.openstacklocal docker[911]: Error response from daemon: network with name gba already exists

**Comment by alexanderkiel** [comment]
Closed by #17
